info:
  component:  price-adapter-rest
server:
  servlet:
    context-path: /${info.component}
spring:
  application:
    name: ${info.component}
  batch:
    isolation:
      level: ISOLATION_READ_COMMITTED
  cloud:
    config:
      name: ${info.component}
  main:
    banner-mode: log
  boot:
    admin:
      client:
        url: http://localhost:8081/server-admin
        username: admin
        password: admin
        instance:
          service-base-url: http://localhost:8082/server-admin
  datasource:
    minimumIdle: 5
    maximumPoolSize: 20
    idleTimeout: 30000
    maxLifetime: 2000000
    connectionTimeout: 300000
    # Configurations to be moved to the cloud config server, I put them here to simplify the testing
# h2     
# file
#   url: jdbc:h2:file:/data/demo
# memory
    url: jdbc:h2:mem:price_readonly
    username: sa
    password: password
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect    
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
  h2:
    console.enabled: true
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  flyway:
    enabled: true
  task:
    executor:
      pool-size: 70
      max-pool-size: 75
      queue-capacity: 80
logging:
  config: config/logback.xml
springdoc:
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    jmx:
      exposure:
        include: '*'
        exclude: env,beans,configprops
    web:
      exposure:
        include: '*'
        exclude: env,beans,configprops
pagination:
  order: ASC